apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnerreportfrontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learnerreportfrontend
  template:
    metadata:
      labels:
        app: learnerreportfrontend
    spec:
      containers:
      - name: learnerreportfrontend
        image: subhra11/learnerreportfrontend:v11
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
